---
# 1.- Crear usuario y grupo
# 2.- Instalar JAVA
# 3.- Crear directorio para Tomcat
# 4.- Descargar y descomprimir el software
# 5.- Asociar el usuario y el grupo
# 6.- Crear un fichero para el arranque con SYSTEMD
# 7.- Arrancar el servicio

- name: Instalar Tomcat
  hosts: ubuntu
  vars:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.42/bin/apache-tomcat-10.1.42.tar.gz

  tasks:
  - name: Crear unsuario
    ansible.builtin.user:
      name: tomcat

  - name: Crear grupo
    ansible.builtin.group:
      name: tomcat

  - name: Instalando JAVA
    ansible.builtin.apt:
      name: default-jdk
      state: present
      update_cache: true

  - name: Creando directorio Tomcat
    ansible.builtin.file:
      path: /opt/tomcat
      state: directory
      owner: tomcat
      group: tomcat
      mode: '0755'
      recurse: true
  
  - name: Descargando y descomprimiendo Tomcat
    ansible.builtin.unarchive:
      src: "{{url}}"
      dest: /opt/tomcat
      remote_src: true
      extra_opts: [--strip-components=1]

  - name: Cambiando permisos en la carpeta Tomcat
    ansible.builtin.file:
      path: /opt/tomcat
      state: directory
      owner: tomcat
      group: tomcat
      mode: '0755'
      recurse: true

  - name: Creando fichero SYSTEMD
    ansible.builtin.copy:
      content: |-
        [Unit]
        Description=Servicio Tomcat
        Requires=network.target
        After=network.target

        [Service]
        Type=forking
        User=tomcat
        Environment="CATALINA_PID=/opt/tomcat/logs/tomcat.pid"
        Environment="CATALINA_BASE=/opt/tomcat/"
        Environment="CATALINA_HOME=/opt/tomcat/"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        ExecStart=/opt/tomcat/bin/startup.sh
        ExecStop=/opt/tomcat/bin/shutdown.sh
        RestartSec=on-abnormal

        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/tomcat.service
  
  - name: Arrancando Tomcat
    ansible.builtin.service:
      name: tomcat
      state: started
